version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports: 
      - '5000:5000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 app:app